
project_id = "gqceeliuclgzjzmubywy"

[auth.external.google]
enabled = true

[functions.send-ticket-email]
verify_jwt = true

[functions.decrement-tier-quantity]
verify_jwt = true

[functions.secure-cart-ops]
verify_jwt = true

[functions.get-balance]
verify_jwt = true

[functions.top-up-balance]
verify_jwt = true

[functions.get-transactions]
verify_jwt = true

[functions.first-atlantic-webhook]
verify_jwt = false
