// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqceeliuclgzjzmubywy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxY2VlbGl1Y2xnemp6bXVieXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MDY4NDgsImV4cCI6MjA2MTk4Mjg0OH0.-ItatSGo0cojPhLHeWP8dOr72-eca-RsSf0T5Q7Kfa0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);